### ISSUE TITLE
Otosert

### ISSUE THREAD

**Issue by hegyhati** [Teaching-projects/SZE-ProgCpp-2018-Kepfelismero#1]
Legyen egy ilyen konfig fajl, es annak megfeleloen mukodjon:
```
Hamburger kepek/hamburger/
Stop kepek/tablak/stop
...


Test: Tesztkepek/kepsorozat1/
```
Es akkor mindegyikre mondja meg, hogy mit talalt ott.

**Comment by attilanatz** [comment]
Frissítettem a kódot, valamint feltöltöttem a pdf-et is.

Köszönöm @hegyhati

**Comment by hegyhati** [comment]
@attilanatz szuper, sok sikert a tobbi vizsgahoz!
